'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'th' | 'en' | 'fr' | 'zh' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  th: {
    'nav.wine': 'ไวน์',
    'nav.accessories': 'อุปกรณ์',
    'nav.coolers': 'ตู้แช่ไวน์',
    'nav.recommended': 'สินค้าแนะนำ',
    'nav.brands': 'แบรนด์',
    'nav.articles': 'บทความ',
    'auth.register': 'สมัครสมาชิก',
    'auth.login': 'เข้าสู่ระบบ',
    'auth.login_title': 'เข้าสู่ระบบ',
    'auth.register_title': 'สร้างบัญชีใหม่',
    'auth.no_account': 'ยังไม่มีบัญชี?',
    'auth.have_account': 'มีบัญชีอยู่แล้ว?',
    'auth.username': 'ชื่อผู้ใช้งาน',
    'auth.password': 'รหัสผ่าน',
    'auth.confirm_password': 'ยืนยันรหัสผ่าน',
    'auth.first_name': 'ชื่อ',
    'auth.last_name': 'นามสกุล',
    'auth.email': 'อีเมล',
    'auth.phone': 'เบอร์โทรศัพท์',
    'auth.forgot_password': 'ลืมรหัสผ่าน?',
    'auth.or_continue_with': 'หรือดำเนินการต่อด้วย',
    'auth.register_terms': 'โดยการลงทะเบียนหมายความว่าคุณยอมรับใน ข้อกำหนดและเงื่อนไข และ นโยบายความเป็นส่วนตัว',
    'auth.password_hint': 'รหัสผ่านควรมีความยาว 8 ตัวอักษรขึ้นไป ประกอบด้วยตัวอักษรภาษาอังกฤษและตัวเลข',
    'auth.error_title': 'เกิดข้อผิดพลาด',
    'auth.error_mismatch': 'รหัสผ่านไม่ตรงกัน',
    'auth.error_unexpected': 'เกิดข้อผิดพลาดที่ไม่คาดคิด กรุณาลองใหม่อีกครั้ง',
    'cart.title': 'ตะกร้าของฉัน',
    'cart.items': 'รายการ',
    'cart.empty': 'ตะกร้าของคุณว่างเปล่า',
    'cart.favorite': 'รายการโปรด',
    'cart.remove': 'ลบ',
    'cart.clear': 'ล้างตะกร้า',
    'cart.update': 'อัพเดทตะกร้าสินค้า',
    'cart.promo_code': 'ใช้รหัสส่วนลด',
    'cart.promo_placeholder': 'กรุณากรอกรหัสส่วนลด',
    'cart.apply': 'ใช้',
    'cart.subtotal': 'ราคาสินค้า',
    'cart.points': 'คุณได้รับ',
    'cart.pretax': 'ราคาสินค้าก่อนรวมภาษี',
    'cart.tax': 'ภาษี',
    'cart.total': 'ราคาสินค้าหลังรวมภาษี',
    'cart.checkout': 'สั่งซื้อสินค้า',
    'cart.loading': 'กำลังโหลดตะกร้าสินค้า...',
    'search.placeholder': 'ค้นหาในร้านค้า...',
    'header.top_info': 'จัดส่งฟรีเมื่อสั่งซื้อครบ 3,000 บาท',
    'header.store_locator': 'ค้นหาร้านค้า',
    'hero.welcome': 'ยินดีต้อนรับสู่',
    'hero.title': 'คัดสรรไวน์ ระดับพรีเมียม เพื่อคุณโดยเฉพาะ',
    'hero.subtitle': 'ไวน์นำเข้าคุณภาพเยี่ยมจากทั่วโลก จัดส่งถึงบ้านคุณภายใน 24 ชั่วโมง',
    'hero.cta_all': 'ดูไวน์ทั้งหมด',
    'hero.cta_more': 'เรียนรู้เพิ่มเติม',
    'hero.stats.items': 'รายการไวน์',
    'hero.stats.brands': 'แบรนด์ชั้นนำ',
    'hero.stats.customers': 'ลูกค้าพึงพอใจ',
    'products.title': 'คอลเลกชันไวน์พรีเมียม',
    'products.subtitle': 'สัมผัสรสชาติระดับพรีเมียมจากทั่วทุกมุมโลก คัดสรรมาเพื่อคุณโดยเฉพาะ',
    'products.filter.all': 'ทั้งหมด',
    'products.filter.red': 'ไวน์แดง',
    'products.filter.white': 'ไวน์ขาว',
    'products.filter.rose': 'โรเซ่',
    'products.filter.premium': 'พรีเมียม',
    'products.api_unavailable': 'API ไม่พร้อมใช้งาน',
    'products.load_error_title': 'ยังโหลดรายการสินค้าไม่ได้',
    'products.load_error_desc': 'API ภายนอกอาจกำลัง cold start หรือไม่พร้อมใช้งาน ลองรีเฟรชหน้าอีกครั้งในอีกสักครู่',
    'products.not_found': 'ไม่พบรายการไวน์ในหมวดหมู่ที่เลือก',
    'products.in_stock': 'ในคลัง',
    'products.price_label': 'ราคา',
    'products.select': 'เลือก',
    'products.classic': 'คลาสสิก',
    'products.wine_label': 'ไวน์',
    'products.red_wine_label': 'ไวน์แดง',
    'products.white_wine_label': 'ไวน์ขาว',
    'products.rose_wine_label': 'โรเซ่',
    'account.title': 'บัญชีผู้ใช้',
    'account.payment_confirm': 'ยืนยันการชำระเงิน',
    'account.profile': 'ข้อมูลส่วนตัว',
    'account.addresses': 'สมุดที่อยู่',
    'account.orders': 'คำสั่งซื้อ',
    'account.favorites': 'รายการโปรดของฉัน',
    'account.privacy': 'ตั้งค่าความเป็นส่วนตัว',
    'account.reviews': 'รีวิวของฉัน',
    'account.points': 'คะแนนสะสมของฉัน',
    'account.logout': 'ออกจากระบบ',
    'account.your_points': 'คะแนนของคุณ',
    'account.user_info': 'ข้อมูลผู้ใช้',
    'account.address_title': 'ที่อยู่',
    'account.first_name': 'ชื่อ',
    'account.last_name': 'นามสกุล',
    'account.phone': 'หมายเลขโทรศัพท์',
    'account.company': 'บริษัท',
    'account.address_label': 'ที่อยู่',
    'account.country': 'ประเทศ',
    'account.province': 'จังหวัด',
    'account.district': 'เขต/อำเภอ',
    'account.sub_district': 'แขวง/ตำบล',
    'account.zipcode': 'รหัสไปรษณีย์',
    'account.select_province': 'กรุณาเลือกจังหวัด',
    'account.select_district': 'กรุณาเลือกอำเภอ',
    'account.select_sub_district': 'กรุณาเลือกตำบล',
    'account.use_shipping': 'ใช้เป็นที่อยู่สำหรับการจัดส่ง',
    'account.use_billing': 'ใช้เป็นที่อยู่สำหรับการออกใบเสร็จ',
    'account.save_address': 'บันทึกที่อยู่',
    'account.saving': 'กำลังบันทึก...',
    'account.loading_data': 'กำลังโหลดข้อมูล...',
    'account.save_success': 'บันทึกที่อยู่เรียบร้อยแล้ว',
    'account.save_error': 'เกิดข้อผิดพลาดในการบันทึกที่อยู่ กรุณาลองใหม่อีกครั้ง',
    'nav.home': 'หน้าหลัก',
    'common.edit': 'แก้ไข',
    'account.change_password': 'เปลี่ยนรหัสผ่าน',
    'account.newsletter': 'จดหมายข่าว',
    'account.no_newsletter': 'คุณยังไม่ได้สมัครรับจดหมายข่าวของเรา',
    'account.subscribe_newsletter': 'สมัครสมาชิกจดหมายข่าว',
    'account.manage_addresses': 'จัดการที่อยู่',
    'account.billing_address': 'ที่อยู่สำหรับออกใบเสร็จ / ใบกำกับภาษี',
    'account.shipping_address': 'ที่อยู่จัดส่งเริ่มต้น',
    'account.no_billing_address': 'คุณยังไม่มีข้อมูลที่อยู่สำหรับออกใบเสร็จ',
    'account.no_shipping_address': 'คุณยังไม่ได้เลือกที่อยู่จัดส่งหลัก',
    'account.edit_address': 'แก้ไขที่อยู่',
    'account.docs_title': 'เอกสารการลงทะเบียน',
    'account.docs_list_title': 'เอกสารดังต่อไปนี้',
    'account.doc_liquor_license': 'ใบอนุญาตจำหน่ายสุรา ประเภท 1 และ/หรือ 2 (รายปี)',
    'account.doc_id_certificate': 'หนังสือรับรองบริษัท / ห้างหุ้นส่วนจำกัด (หจก.) / สำเนาบัตรประชาชน (บุคคลธรรมดา)',
    'account.doc_vat_certificate': 'ใบจดทะเบียนภาษีมูลค่าเพิ่ม (ภพ.20) (ถ้ามี)',
    'account.no_file_selected': 'ไม่ได้เลือกไฟล์ใด',
    'account.choose_file': 'เลือกไฟล์',
    'account.add_more_files': 'เลือกไฟล์อื่นเพิ่มเติม',
    'account.docs_hint': 'คุณต้องอัปโหลดไฟล์หนังสือรับรองบริษัท / ห้างหุ้นส่วนจำกัด (หจก.) / สำเนาบัตรประชาชน (บุคคลธรรมดา) ใบอนุญาตจำหน่ายสุรา ประเภท 1 และ/หรือ 2 (รายปี) และใบจดทะเบียนภาษีมูลค่าเพิ่ม',
    'account.no_orders': 'คุณไม่มีประวัติการสั่งซื้อ',
    'order.number': 'คำสั่งซื้อ',
    'order.date': 'วันที่สั่งซื้อ',
    'order.total': 'ยอดรวม',
    'order.payment': 'วิธีชำระเงิน',
    'order.details': 'ดูรายละเอียด',
    'account.member_type': 'ประเภทสมาชิก',
    'account.gender': 'เพศ',
    'account.gender_male': 'ชาย',
    'account.gender_female': 'หญิง',
    'account.gender_other': 'อื่นๆ',
    'account.change_email': 'เปลี่ยนอีเมล',
    'common.save': 'บันทึก',
    'footer.about': 'เกี่ยวกับเรา',
    'footer.contact': 'ติดต่อเรา',
    'footer.brand_desc': 'ร้านไวน์และเครื่องดื่มระดับพรีเมียม คัดสรรจากทั่วโลก พร้อมส่งถึงบ้านคุณ',
    'footer.categories': 'หมวดหมู่',
    'footer.red_wine': 'ไวน์แดง',
    'footer.white_wine': 'ไวน์ขาว',
    'footer.sparkling': 'สปาร์คกลิ้ง',
    'footer.gifts': 'ของขวัญ',
    'footer.services': 'บริการลูกค้า',
    'footer.how_to_order': 'วิธีสั่งซื้อ',
    'footer.tracking': 'ติดตามสินค้า',
    'footer.returns': 'คืนสินค้า',
    'footer.faq': 'FAQ',
    'footer.contact_title': 'ติดต่อ',
    'footer.delivery_by': 'จัดส่งโดย',
    'footer.payment': 'การชำระเงิน',
    'products.members_only_title': 'สินค้าเฉพาะสมาชิก',
    'products.members_only_desc': 'กรุณาเข้าสู่ระบบเพื่อเรียกดูรายการสินค้าพรีเมียมและรับสิทธิพิเศษสำหรับสมาชิก Bottle Club เท่านั้น',
  },
  en: {
    'nav.wine': 'Wine',
    'nav.accessories': 'Accessories',
    'nav.coolers': 'Wine Coolers',
    'nav.recommended': 'Recommended',
    'nav.brands': 'Brands',
    'nav.articles': 'Articles',
    'auth.register': 'Register',
    'auth.login': 'Login',
    'auth.login_title': 'Login',
    'auth.register_title': 'Create New Account',
    'auth.no_account': "Don't have an account?",
    'auth.have_account': 'Already have an account?',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.first_name': 'First Name',
    'auth.last_name': 'Last Name',
    'auth.email': 'Email',
    'auth.phone': 'Phone Number',
    'auth.forgot_password': 'Forgot Password?',
    'auth.or_continue_with': 'Or continue with',
    'auth.register_terms': 'By registering, you agree to our Terms & Conditions and Privacy Policy',
    'auth.password_hint': 'Password should be at least 8 characters long, including letters and numbers',
    'auth.error_title': 'Error Occurred',
    'auth.error_mismatch': 'Passwords do not match',
    'auth.error_unexpected': 'An unexpected error occurred. Please try again',
    'cart.title': 'My Cart',
    'cart.items': 'items',
    'cart.empty': 'Your cart is empty',
    'cart.favorite': 'Favorite',
    'cart.remove': 'Remove',
    'cart.clear': 'Clear Cart',
    'cart.update': 'Update Cart',
    'cart.promo_code': 'Use Promo Code',
    'cart.promo_placeholder': 'Enter promo code',
    'cart.apply': 'Apply',
    'cart.subtotal': 'Subtotal',
    'cart.points': 'You earn',
    'cart.pretax': 'Pre-tax Total',
    'cart.tax': 'Tax',
    'cart.total': 'Total (Inc. Tax)',
    'cart.checkout': 'Checkout',
    'cart.loading': 'Loading cart...',
    'search.placeholder': 'Search entire store here...',
    'header.top_info': 'Free delivery on orders over ฿3,000',
    'header.store_locator': 'Store Locator',
    'hero.welcome': 'Welcome to',
    'hero.title': 'Premium Wine Selections Curated For You',
    'hero.subtitle': 'Quality imported wines from around the world, delivered to your door within 24 hours.',
    'hero.cta_all': 'Shop All Wines',
    'hero.cta_more': 'Learn More',
    'hero.stats.items': 'Wine Items',
    'hero.stats.brands': 'Top Brands',
    'hero.stats.customers': 'Happy Customers',
    'products.title': 'Premium Wine Collection',
    'products.subtitle': 'Experience premium taste from around the globe, curated for you.',
    'products.filter.all': 'All',
    'products.filter.red': 'Red Wine',
    'products.filter.white': 'White Wine',
    'products.filter.rose': 'Rosé',
    'products.filter.premium': 'Premium',
    'products.api_unavailable': 'API Unavailable',
    'products.load_error_title': 'Unable to Load Products',
    'products.load_error_desc': 'The external API might be cold starting or temporarily unavailable. Please refresh in a moment.',
    'products.not_found': 'No wines found in the selected category.',
    'products.in_stock': 'In Stock',
    'products.price_label': 'Price',
    'products.select': 'Select',
    'products.classic': 'Classic',
    'products.wine_label': 'Wine',
    'products.red_wine_label': 'Red Wine',
    'products.white_wine_label': 'White Wine',
    'products.rose_wine_label': 'Rosé',
    'account.title': 'My Account',
    'account.payment_confirm': 'Payment Confirmation',
    'account.profile': 'Personal Profile',
    'account.addresses': 'Address Book',
    'account.orders': 'Orders',
    'account.favorites': 'My Favorites',
    'account.privacy': 'Privacy Settings',
    'account.reviews': 'My Reviews',
    'account.points': 'My Reward Points',
    'account.logout': 'Logout',
    'account.your_points': 'Your Points',
    'account.user_info': 'User Information',
    'account.address_title': 'Address',
    'account.first_name': 'First Name',
    'account.last_name': 'Last Name',
    'account.phone': 'Phone Number',
    'account.company': 'Company',
    'account.address_label': 'Address',
    'account.country': 'Country',
    'account.province': 'Province',
    'account.district': 'District',
    'account.sub_district': 'Sub-district',
    'account.zipcode': 'Zipcode',
    'account.select_province': 'Please select province',
    'account.select_district': 'Please select district',
    'account.select_sub_district': 'Please select sub-district',
    'account.use_shipping': 'Use as shipping address',
    'account.use_billing': 'Use as billing address',
    'account.save_address': 'Save Address',
    'account.saving': 'Saving...',
    'account.loading_data': 'Loading data...',
    'account.save_success': 'Address saved successfully',
    'account.save_error': 'An error occurred while saving the address. Please try again.',
    'nav.home': 'Home',
    'common.edit': 'Edit',
    'account.change_password': 'Change Password',
    'account.newsletter': 'Newsletter',
    'account.no_newsletter': 'You are not subscribed to our newsletter.',
    'account.subscribe_newsletter': 'Subscribe to newsletter',
    'account.manage_addresses': 'Manage Addresses',
    'account.billing_address': 'Billing Address / Tax Invoice',
    'account.shipping_address': 'Default Shipping Address',
    'account.no_billing_address': 'You have no billing address info.',
    'account.no_shipping_address': 'You have not selected a primary shipping address.',
    'account.edit_address': 'Edit Address',
    'account.docs_title': 'Registration Documents',
    'account.docs_list_title': 'The following documents',
    'account.doc_liquor_license': 'Liquor License Type 1 and/or 2 (Annual)',
    'account.doc_id_certificate': 'Company Certificate / Partnership / ID Copy (Individual)',
    'account.doc_vat_certificate': 'VAT Registration (PP.20) (If any)',
    'account.no_file_selected': 'No file selected',
    'account.choose_file': 'Choose File',
    'account.add_more_files': 'Add More Files',
    'account.docs_hint': 'You must upload Company Certificate / ID Copy, Liquor License, and VAT Registration (if applicable).',
    'account.no_orders': 'You have no order history.',
    'order.number': 'Order',
    'order.date': 'Order Date',
    'order.total': 'Total',
    'order.payment': 'Payment Method',
    'order.details': 'View Details',
    'account.member_type': 'Member Type',
    'account.gender': 'Gender',
    'account.gender_male': 'Male',
    'account.gender_female': 'Female',
    'account.gender_other': 'Other',
    'account.change_email': 'Change Email',
    'common.save': 'Save',
    'footer.about': 'About Us',
    'footer.contact': 'Contact Us',
    'footer.brand_desc': 'Premium wine and spirits shop, curated from around the world, delivered to your door.',
    'footer.categories': 'Categories',
    'footer.red_wine': 'Red Wine',
    'footer.white_wine': 'White Wine',
    'footer.sparkling': 'Sparkling',
    'footer.gifts': 'Gifts',
    'footer.services': 'Customer Service',
    'footer.how_to_order': 'How to Order',
    'footer.tracking': 'Track Order',
    'footer.returns': 'Returns',
    'footer.faq': 'FAQ',
    'footer.contact_title': 'Contact',
    'footer.delivery_by': 'DELIVERY BY',
    'footer.payment': 'PAYMENT',
    'products.members_only_title': 'Members Only Products',
    'products.members_only_desc': 'Please log in to view premium products and receive exclusive benefits for Bottle Club members only.',
  },
  fr: {
    'nav.wine': 'Vin',
    'nav.accessories': 'Accessoires',
    'nav.coolers': 'Caves à vin',
    'nav.recommended': 'Recommandé',
    'nav.brands': 'Marques',
    'nav.articles': 'Articles',
    'auth.register': "S'inscrire",
    'auth.login': 'Connexion',
    'search.placeholder': 'Rechercher dans la boutique...',
    'header.top_info': 'Livraison gratuite dès 3 000 ฿',
    'hero.welcome': 'Bienvenue à',
    'hero.title': 'Sélections de Vins Premium Conçues Pour Vous',
    'hero.subtitle': 'Vins importés de qualité du monde entier, livrés à votre porte sous 24h.',
    'hero.cta_all': 'Voir Tous Les Vins',
    'hero.cta_more': 'En Savoir Plus',
    'hero.stats.items': 'Types de Vin',
    'hero.stats.brands': 'Grandes Marques',
    'hero.stats.customers': 'Clients Satisfaits',
    'products.title': 'Collection de Vins Premium',
    'products.subtitle': 'Faites l\'expérience du goût haut de gamme du monde entier.',
    'products.filter.all': 'Tout',
    'products.filter.red': 'Vin Rouge',
    'products.filter.white': 'Vin Blanc',
    'products.filter.rose': 'Rosé',
    'products.filter.premium': 'Premium',
    'footer.about': 'À propos',
    'footer.contact': 'Contactez-nous',
    'auth.register_title': 'Créer un nouveau compte',
    'auth.login_title': 'Connexion',
    'auth.no_account': 'Pas encore de compte?',
    'auth.have_account': 'Déjà un compte?',
    'auth.username': "Nom d'utilisateur",
    'auth.password': 'Mot de passe',
    'auth.confirm_password': 'Confirmer le mot de passe',
    'auth.first_name': 'Prénom',
    'auth.last_name': 'Nom',
    'auth.email': 'E-mail',
    'auth.phone': 'Numéro de téléphone',
    'auth.forgot_password': 'Mot de passe oublié?',
    'auth.or_continue_with': 'Ou continuer avec',
    'auth.register_terms': 'En vous inscrivant, vous acceptez nos Conditions Générales et notre Politique de Confidentialité',
    'auth.password_hint': 'Le mot de passe doit comporter au moins 8 caractères, dont des lettres et des chiffres',
    'auth.error_title': 'Une erreur est survenue',
    'auth.error_mismatch': 'Les mots de passe ne correspondent pas',
    'auth.error_unexpected': 'Une erreur inattendue est survenue. Veuillez réessayer',
    'cart.title': 'Mon Panier',
    'cart.items': 'articles',
    'cart.empty': 'Votre panier est vide',
    'cart.favorite': 'Favori',
    'cart.remove': 'Supprimer',
    'cart.clear': 'Vider le panier',
    'cart.update': 'Mettre à jour le panier',
    'cart.promo_code': 'Utiliser un code promo',
    'cart.promo_placeholder': 'Entrez le code promo',
    'cart.apply': 'Appliquer',
    'cart.subtotal': 'Sous-total',
    'cart.points': 'Vous gagnez',
    'cart.pretax': 'Total hors taxes',
    'cart.tax': 'Taxe',
    'cart.total': 'Total (TTC)',
    'cart.checkout': 'Payer',
    'cart.loading': 'Chargement du panier...',
    'account.title': 'Mon Compte',
    'account.payment_confirm': 'Confirmation de Paiement',
    'account.profile': 'Profil Personnel',
    'account.addresses': 'Carnet d\'Adresses',
    'account.orders': 'Commandes',
    'account.favorites': 'Mes Favoris',
    'account.privacy': 'Paramètres de Confidentialité',
    'account.reviews': 'Mes Avis',
    'account.points': 'Mes Points de Récompense',
    'account.logout': 'Déconnexion',
    'account.your_points': 'Vos Points',
    'account.user_info': 'Informations Utilisateur',
    'account.address_title': 'Adresse',
    'account.first_name': 'Prénom',
    'account.last_name': 'Nom',
    'account.phone': 'Numéro de téléphone',
    'account.company': 'Entreprise',
    'account.address_label': 'Adresse',
    'account.country': 'Pays',
    'account.province': 'Province',
    'account.district': 'District',
    'account.sub_district': 'Sous-district',
    'account.zipcode': 'Code postal',
    'account.select_province': 'Veuillez sélectionner la province',
    'account.select_district': 'Veuillez sélectionner le district',
    'account.select_sub_district': 'Veuillez sélectionner le sous-district',
    'account.use_shipping': 'Utiliser comme adresse de livraison',
    'account.use_billing': 'Utiliser comme adresse de facturation',
    'account.save_address': 'Enregistrer l\'Adresse',
    'account.saving': 'Enregistrement...',
    'account.loading_data': 'Chargement des données...',
    'account.save_success': 'Adresse enregistrée avec succès',
    'account.save_error': 'Une erreur est survenue lors de l\'enregistrement de l\'adresse. Veuillez réessayer.',
    'nav.home': 'Accueil',
    'common.edit': 'Modifier',
    'account.change_password': 'Changer le mot de passe',
    'account.newsletter': 'Newsletter',
    'account.no_newsletter': 'Vous n\'êtes pas abonné à notre newsletter.',
    'account.subscribe_newsletter': 'S\'abonner à la newsletter',
    'account.manage_addresses': 'Gérer les adresses',
    'account.billing_address': 'Adresse de facturation / Facture fiscale',
    'account.shipping_address': 'Adresse de livraison par défaut',
    'account.no_billing_address': 'Vous n\'avez pas d\'adresse de facturation.',
    'account.no_shipping_address': 'Vous n\'avez pas sélectionné d\'adresse de livraison principale.',
    'account.edit_address': 'Modifier l\'adresse',
    'account.docs_title': 'Documents d\'enregistrement',
    'account.docs_list_title': 'Les documents suivants',
    'account.doc_liquor_license': 'Licence de vente d\'alcool Type 1 et/ou 2 (Annuelle)',
    'account.doc_id_certificate': 'Certificat d\'entreprise / Copie d\'identité (Individuel)',
    'account.doc_vat_certificate': 'Enregistrement à la TVA (Si applicable)',
    'account.no_file_selected': 'Aucun fichier sélectionné',
    'account.choose_file': 'Choisir un fichier',
    'account.add_more_files': 'Ajouter d\'autres fichiers',
    'account.docs_hint': 'Vous devez télécharger le certificat d\'entreprise / copie d\'identité, la licence d\'alcool et l\'enregistrement à la TVA.',
    'account.no_orders': 'Vous n\'avez pas d\'historique de commande.',
    'order.number': 'Commande',
    'order.date': 'Date de commande',
    'order.total': 'Total',
    'order.payment': 'Mode de paiement',
    'order.details': 'Voir les détails',
    'account.member_type': 'Type de membre',
    'account.gender': 'Genre',
    'account.gender_male': 'Homme',
    'account.gender_female': 'Femme',
    'account.gender_other': 'Autre',
    'account.change_email': 'Modifier l\'e-mail',
    'common.save': 'Enregistrer',
    'footer.brand_desc': 'Boutique de vins et spiritueux premium, sélectionnés dans le monde entier, livrés chez vous.',
    'footer.categories': 'Catégories',
    'footer.red_wine': 'Vin Rouge',
    'footer.white_wine': 'Vin Blanc',
    'footer.sparkling': 'Pétillant',
    'footer.gifts': 'Cadeaux',
    'footer.services': 'Service Client',
    'footer.how_to_order': 'Comment Commander',
    'footer.tracking': 'Suivi de Commande',
    'footer.returns': 'Retours',
    'footer.faq': 'FAQ',
    'footer.contact_title': 'Contact',
    'footer.delivery_by': 'LIVRAISON PAR',
    'footer.payment': 'PAIEMENT',
    'products.members_only_title': 'Produits réservés aux membres',
    'products.members_only_desc': 'Veuillez vous connecter pour voir les produits premium et bénéficier d\'avantages exclusifs réservés aux membres du Bottle Club.',
  },
  zh: {
    'nav.wine': '葡萄酒',
    'nav.accessories': '配件',
    'nav.coolers': '酒柜',
    'nav.recommended': '推荐产品',
    'nav.brands': '品牌',
    'nav.articles': '文章',
    'auth.register': '注册',
    'auth.login': '登录',
    'search.placeholder': '在这里搜索整个商店...',
    'header.top_info': '订单满 3,000 ฿ 免运费',
    'hero.welcome': '欢迎来到',
    'hero.title': '为您精心挑选的高级葡萄酒',
    'hero.subtitle': '来自世界各地的优质进口葡萄酒，24小时内送货上门。',
    'hero.cta_all': '购买所有葡萄酒',
    'hero.cta_more': '了解更多',
    'hero.stats.items': '葡萄酒品种',
    'hero.stats.brands': '顶级品牌',
    'hero.stats.customers': '满意客户',
    'products.title': '顶级葡萄酒系列',
    'products.subtitle': '体验全球顶级品质，为您精心挑选。',
    'products.filter.all': '全部',
    'products.filter.red': '红葡萄酒',
    'products.filter.white': '白葡萄酒',
    'products.filter.rose': '桃红葡萄酒',
    'products.filter.premium': '特级',
    'footer.about': '关于我们',
    'footer.contact': '联系我们',
    'auth.register_title': '创建新账户',
    'auth.login_title': '登录',
    'auth.no_account': '还没有账户？',
    'auth.have_account': '已有账户？',
    'auth.username': '用户名',
    'auth.password': '密码',
    'auth.confirm_password': '确认密码',
    'auth.first_name': '名字',
    'auth.last_name': '姓氏',
    'auth.email': '电子邮件',
    'auth.phone': '电话号码',
    'auth.forgot_password': '忘记密码？',
    'auth.or_continue_with': '或继续使用',
    'auth.register_terms': '注册即表示您同意我们的条款与条件以及隐私政策',
    'auth.password_hint': '密码应至少包含8个字符，包括字母和数字',
    'auth.error_title': '发生错误',
    'auth.error_mismatch': '密码不匹配',
    'auth.error_unexpected': '发生意外错误。请重试',
    'cart.title': '我的购物车',
    'cart.items': '件商品',
    'cart.empty': '您的购物车是空的',
    'cart.favorite': '收藏',
    'cart.remove': '移除',
    'cart.clear': '清空购物车',
    'cart.update': '更新购物车',
    'cart.promo_code': '使用优惠码',
    'cart.promo_placeholder': '输入优惠码',
    'cart.apply': '应用',
    'cart.subtotal': '小计',
    'cart.points': '您赚取',
    'cart.pretax': '税前总额',
    'cart.tax': '税费',
    'cart.total': '总计（含税）',
    'cart.checkout': '结账',
    'cart.loading': '正在加载购物车...',
    'account.title': '我的账户',
    'account.payment_confirm': '付款确认',
    'account.profile': '个人资料',
    'account.addresses': '地址簿',
    'account.orders': '订单',
    'account.favorites': '我的收藏',
    'account.privacy': '隐私设置',
    'account.reviews': '我的评价',
    'account.points': '我的奖励积分',
    'account.logout': '注销',
    'account.your_points': '您的积分',
    'account.user_info': '用户信息',
    'account.address_title': '地址',
    'account.first_name': '名字',
    'account.last_name': '姓氏',
    'account.phone': '电话号码',
    'account.company': '公司',
    'account.address_label': '地址',
    'account.country': '国家',
    'account.province': '省份',
    'account.district': '区/县',
    'account.sub_district': '街道/乡镇',
    'account.zipcode': '邮政编码',
    'account.select_province': '请选择省份',
    'account.select_district': '请选择区/县',
    'account.select_sub_district': '请选择街道/乡镇',
    'account.use_shipping': '用作送货地址',
    'account.use_billing': '用作账单地址',
    'account.save_address': '保存地址',
    'account.saving': '正在保存...',
    'account.loading_data': '正在加载数据...',
    'account.save_success': '地址保存成功',
    'account.save_error': '保存地址时发生错误。请重试。',
    'nav.home': '首页',
    'common.edit': '编辑',
    'account.change_password': '修改密码',
    'account.newsletter': '新闻通讯',
    'account.no_newsletter': '您尚未订阅我们的新闻通讯。',
    'account.subscribe_newsletter': '订阅新闻通讯',
    'account.manage_addresses': '管理地址',
    'account.billing_address': '账单地址 / 税务发票',
    'account.shipping_address': '默认送货地址',
    'account.no_billing_address': '您没有账单地址信息。',
    'account.no_shipping_address': '您尚未选择主要送货地址。',
    'account.edit_address': '编辑地址',
    'account.docs_title': '注册文件',
    'account.docs_list_title': '以下文件',
    'account.doc_liquor_license': '1类及/或2类酒类销售许可证（年度）',
    'account.doc_id_certificate': '公司营业执照 / 身份证复印件（个人）',
    'account.doc_vat_certificate': '增值税登记证（如果有）',
    'account.no_file_selected': '未选择文件',
    'account.choose_file': '选择文件',
    'account.add_more_files': '添加更多文件',
    'account.docs_hint': '您必须上传公司执照/身份证复印件、酒类许可证和增值税登记证（如果适用）。',
    'account.no_orders': '您没有订单历史。',
    'order.number': '订单',
    'order.date': '订单日期',
    'order.total': '总额',
    'order.payment': '付款方式',
    'order.details': '查看详情',
    'account.member_type': '会员类型',
    'account.gender': '性别',
    'account.gender_male': '男',
    'account.gender_female': '女',
    'account.gender_other': '其他',
    'account.change_email': '修改电子邮件',
    'common.save': '保存',
    'footer.brand_desc': '高级葡萄酒和烈酒商店，精心挑选自 world wide, 送货上门。',
    'footer.categories': '类别',
    'footer.red_wine': '红葡萄酒',
    'footer.white_wine': '白葡萄酒',
    'footer.sparkling': '气泡酒',
    'footer.gifts': '礼物',
    'footer.services': '客户服务',
    'footer.how_to_order': '如何订购',
    'footer.tracking': '订单追踪',
    'footer.returns': '退货',
    'footer.faq': '常见问题',
    'footer.contact_title': '联系',
    'footer.delivery_by': '送货方式',
    'footer.payment': '付款方式',
    'products.members_only_title': '会员专属产品',
    'products.members_only_desc': '请登录以查看高级产品并获得 Bottle Club 会员专属福利。',
  },
  ja: {
    'nav.wine': 'ワイン',
    'nav.accessories': 'アクセサリー',
    'nav.coolers': 'ワインセラー',
    'nav.recommended': 'おすすめ',
    'nav.brands': 'ブランド',
    'nav.articles': '記事',
    'auth.register': '会員登録',
    'auth.login': 'ログイン',
    'search.placeholder': 'ストア内を検索...',
    'header.top_info': '3,000 ฿ 以上のお買い上げで送料無料',
    'hero.welcome': 'ようこそ',
    'hero.title': 'あなたのために厳選されたプレミアムワイン',
    'hero.subtitle': '世界中から輸入された高品質なワインを、24時間以内にお手元へ。',
    'hero.cta_all': 'すべてのワインを見る',
    'hero.cta_more': '詳細を見る',
    'hero.stats.items': 'ワインの種類',
    'hero.stats.brands': 'トップブランド',
    'hero.stats.customers': '満足したお客様',
    'products.title': 'プレミアムワインコレクション',
    'products.subtitle': '世界中のプレミアムな味わいを、あなたのために。',
    'products.filter.all': 'すべて',
    'products.filter.red': '赤ワイン',
    'products.filter.white': '白ワイン',
    'products.filter.rose': 'ロゼ',
    'products.filter.premium': 'プレミアム',
    'footer.about': '私たちについて',
    'footer.contact': 'お問い合わせ',
    'auth.register_title': '新規アカウント作成',
    'auth.login_title': 'ログイン',
    'auth.no_account': 'アカウントをお持ちではありませんか？',
    'auth.have_account': 'すでにアカウントをお持ちですか？',
    'auth.username': 'ユーザー名',
    'auth.password': 'パスワード',
    'auth.confirm_password': 'パスワードの確認',
    'auth.first_name': '名',
    'auth.last_name': '姓',
    'auth.email': 'メールアドレス',
    'auth.phone': '電話番号',
    'auth.forgot_password': 'パスワードをお忘れですか？',
    'auth.or_continue_with': 'または次で続行',
    'auth.register_terms': '登録することにより、利用規約とプライバシーポリシーに同意したことになります',
    'auth.password_hint': 'パスワードは英数字を含む8文字以上である必要があります',
    'auth.error_title': 'エラーが発生しました',
    'auth.error_mismatch': 'パスワードが一致しません',
    'auth.error_unexpected': '予期しないエラーが発生しました。もう一度お試しください',
    'cart.title': 'マイカート',
    'cart.items': '点',
    'cart.empty': 'カートは空です',
    'cart.favorite': 'お気に入り',
    'cart.remove': '削除',
    'cart.clear': 'カートをクリア',
    'cart.update': 'カートを更新',
    'cart.promo_code': 'プロモーションコードを使用',
    'cart.promo_placeholder': 'コードを入力',
    'cart.apply': '適用',
    'cart.subtotal': '小計',
    'cart.points': '獲得ポイント',
    'cart.pretax': '税抜合計',
    'cart.tax': '税金',
    'cart.total': '合計（税込）',
    'cart.checkout': 'レジへ進む',
    'cart.loading': 'カートを読み込み中...',
    'account.title': 'マイアカウント',
    'account.payment_confirm': '支払い確認',
    'account.profile': 'プロフィール',
    'account.addresses': 'アドレス帳',
    'account.orders': '注文履歴',
    'account.favorites': 'お気に入りリスト',
    'account.privacy': 'プライバシー設定',
    'account.reviews': 'マイレビュー',
    'account.points': 'マイポイント',
    'account.logout': 'ログアウト',
    'account.your_points': '保有ポイント',
    'account.user_info': 'ユーザー情報',
    'account.address_title': '住所',
    'account.first_name': '名',
    'account.last_name': '姓',
    'account.phone': '電話番号',
    'account.company': '会社名',
    'account.address_label': '住所',
    'account.country': '国',
    'account.province': '都道府県',
    'account.district': '市区町村',
    'account.sub_district': '町名・番地',
    'account.zipcode': '郵便番号',
    'account.select_province': '都道府県を選択してください',
    'account.select_district': '市区町村を選択してください',
    'account.select_sub_district': '町名・番地を選択してください',
    'account.use_shipping': '配送先住所として使用',
    'account.use_billing': '請求先住所として使用',
    'account.save_address': '住所を保存',
    'account.saving': '保存中...',
    'account.loading_data': 'データを読み込み中...',
    'account.save_success': '住所が正常に保存されました',
    'account.save_error': '住所の保存中にエラーが発生しました。もう一度お試しください。',
    'nav.home': 'ホーム',
    'common.edit': '編集',
    'account.change_password': 'パスワード変更',
    'account.newsletter': 'ニュースレター',
    'account.no_newsletter': 'ニュースレターを購読していません。',
    'account.subscribe_newsletter': 'ニュースレターを購読する',
    'account.manage_addresses': '住所を管理',
    'account.billing_address': '請求先住所 / 税務インボイス',
    'account.shipping_address': 'デフォルト配送先住所',
    'account.no_billing_address': '請求先住所情報がありません。',
    'account.no_shipping_address': '主要な配送先住所が選択されていません。',
    'account.edit_address': '住所を編集',
    'account.docs_title': '登録書類',
    'account.docs_list_title': '以下の書類',
    'account.doc_liquor_license': '酒類販売業免許（第1号および/または第2号）（年間）',
    'account.doc_id_certificate': '会社設立証明書 / 身分証明書コピー（個人）',
    'account.doc_vat_certificate': 'VAT登録（PP.20）（ある場合）',
    'account.no_file_selected': 'ファイルが選択されていません',
    'account.choose_file': 'ファイルを選択',
    'account.add_more_files': 'さらにファイルを追加',
    'account.docs_hint': '会社証明書/身分証明書のコピー、酒類免許、およびVAT登録（該当する場合）をアップロードする必要があります。',
    'account.no_orders': '注文履歴はありません。',
    'order.number': '注文',
    'order.date': '注文日',
    'order.total': '合計',
    'order.payment': '支払い方法',
    'order.details': '詳細を見る',
    'account.member_type': '会員種別',
    'account.gender': '性別',
    'account.gender_male': '男性',
    'account.gender_female': '女性',
    'account.gender_other': 'その他',
    'account.change_email': 'メールアドレス変更',
    'common.save': '保存',
    'footer.brand_desc': '世界中から厳選されたプレミアムなワインとスピリッツのショップ。ご自宅までお届けします。',
    'footer.categories': 'カテゴリー',
    'footer.red_wine': '赤ワイン',
    'footer.white_wine': '白ワイン',
    'footer.sparkling': 'スパークリング',
    'footer.gifts': 'ギフト',
    'footer.services': 'カスタマーサービス',
    'footer.how_to_order': '注文方法',
    'footer.tracking': '注文追跡',
    'footer.returns': '返品について',
    'footer.faq': 'よくある質問',
    'footer.contact_title': '連絡先',
    'footer.delivery_by': '配送業者',
    'footer.payment': 'お支払い方法',
    'products.members_only_title': '会員限定商品',
    'products.members_only_desc': 'プレミアム商品の閲覧や、Bottle Club会員限定の特典を受けるにはログインしてください。',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('th');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && translations[savedLang]) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  };

  const t = (key: string) => {
    const langData = translations[language] as Record<string, string>;
    return langData[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
